name: terraform-ci
on: [push, pull_request]
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt (check)
        run: terraform fmt -check
      - name: Terraform init (no backend)
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: TFLint init and run
        run: tflint --init && tflint
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
